class ExportService {
  constructor(db) {
    this.db = db;
  }

  getBrandData(brandId) {
    const brand = this.db.prepare('SELECT * FROM brands WHERE id = ?').get(brandId);
    const colors = this.db.prepare('SELECT * FROM colors WHERE brand_id = ? ORDER BY sort_order').all(brandId);
    const fonts = this.db.prepare('SELECT * FROM fonts WHERE brand_id = ?').all(brandId);
    return { brand, colors, fonts };
  }

  toCSS(brandId) {
    const { brand, colors, fonts } = this.getBrandData(brandId);
    let css = `/* ${brand.name} — Brand Kit CSS Variables */\n`;
    css += `/* Generated by Brand Kit Manager */\n\n`;
    css += `:root {\n`;
    css += `  /* Colors */\n`;
    for (const color of colors) {
      const varName = color.css_variable || `--color-${color.name.toLowerCase().replace(/\s+/g, '-')}`;
      css += `  ${varName}: ${color.hex};\n`;
    }
    if (fonts.length > 0) {
      css += `\n  /* Typography */\n`;
      for (const font of fonts) {
        const varName = `--font-${font.category}`;
        css += `  ${varName}: '${font.family}', sans-serif;\n`;
      }
    }
    css += `}\n`;
    return css;
  }

  toSCSS(brandId) {
    const { brand, colors, fonts } = this.getBrandData(brandId);
    let scss = `// ${brand.name} — Brand Kit SCSS Variables\n`;
    scss += `// Generated by Brand Kit Manager\n\n`;
    scss += `// Colors\n`;
    for (const color of colors) {
      const varName = `$${color.name.toLowerCase().replace(/\s+/g, '-')}`;
      scss += `${varName}: ${color.hex};\n`;
    }
    if (fonts.length > 0) {
      scss += `\n// Typography\n`;
      for (const font of fonts) {
        scss += `$font-${font.category}: '${font.family}', sans-serif;\n`;
      }
    }
    return scss;
  }

  toJSON(brandId) {
    const { brand, colors, fonts } = this.getBrandData(brandId);
    const output = {
      name: brand.name,
      description: brand.description,
      colors: {},
      typography: {},
    };
    for (const color of colors) {
      const key = color.name.toLowerCase().replace(/\s+/g, '_');
      output.colors[key] = {
        value: color.hex,
        category: color.category,
        cssVariable: color.css_variable,
      };
    }
    for (const font of fonts) {
      output.typography[font.category] = {
        family: font.family,
        weight: font.weight,
        style: font.style,
      };
    }
    return JSON.stringify(output, null, 2);
  }

  toFigmaTokens(brandId) {
    const { brand, colors, fonts } = this.getBrandData(brandId);
    const tokens = { [brand.name]: { colors: {}, typography: {} } };
    for (const color of colors) {
      const key = color.name.toLowerCase().replace(/\s+/g, '-');
      tokens[brand.name].colors[key] = {
        value: color.hex,
        type: 'color',
        description: `${color.category} color`,
      };
    }
    for (const font of fonts) {
      tokens[brand.name].typography[font.category] = {
        value: { fontFamily: font.family, fontWeight: font.weight },
        type: 'typography',
      };
    }
    return JSON.stringify(tokens, null, 2);
  }
}

module.exports = ExportService;
